version: '3'
services:
  strapi:
    container_name: "strapi"
    build:
      context: .
    #    volumes:
    #      - .:/app
    ports:
      - '1337:1337'
    privileged: true
    restart: unless-stopped
    networks:
      - fullstack

  shopping-project:
    image: 'mikehsu0618/shopping-project'
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - fullstack

  shopping-manager:
    image: 'mikehsu0618/shopping-manager'
    ports:
      - '8000:80'
    restart: unless-stopped
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
